// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy.proto

package httpgrpc

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// All valid HTTP method names
type Method int32

const (
	Method_UNKNOWN Method = 0
	Method_GET     Method = 1
	Method_HEAD    Method = 2
	Method_POST    Method = 3
	Method_PUT     Method = 4
	Method_DELETE  Method = 5
	Method_CONNECT Method = 6
	Method_OPTIONS Method = 7
	Method_TRACE   Method = 8
	Method_PATCH   Method = 9
)

var Method_name = map[int32]string{
	0: "UNKNOWN",
	1: "GET",
	2: "HEAD",
	3: "POST",
	4: "PUT",
	5: "DELETE",
	6: "CONNECT",
	7: "OPTIONS",
	8: "TRACE",
	9: "PATCH",
}

var Method_value = map[string]int32{
	"UNKNOWN": 0,
	"GET":     1,
	"HEAD":    2,
	"POST":    3,
	"PUT":     4,
	"DELETE":  5,
	"CONNECT": 6,
	"OPTIONS": 7,
	"TRACE":   8,
	"PATCH":   9,
}

func (x Method) String() string {
	return proto.EnumName(Method_name, int32(x))
}

func (Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{0}
}

// The request data from the HTTP request
type Request struct {
	// HTTP method from requestor
	Method Method `protobuf:"varint,1,opt,name=method,proto3,enum=httpgrpc.Method" json:"method,omitempty"`
	// Desired procedure name
	Procedure string `protobuf:"bytes,2,opt,name=procedure,proto3" json:"procedure,omitempty"`
	// JSON payload of the request, if present
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Query params of the request, if present
	Params               []*QueryParam `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMethod() Method {
	if m != nil {
		return m.Method
	}
	return Method_UNKNOWN
}

func (m *Request) GetProcedure() string {
	if m != nil {
		return m.Procedure
	}
	return ""
}

func (m *Request) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Request) GetParams() []*QueryParam {
	if m != nil {
		return m.Params
	}
	return nil
}

// The response to send to the requestor
type Response struct {
	// Manually set status code rather than rely on error-handling at the proxy
	StatusCode uint32 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// JSON data to return to the requestor
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Response) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// Clearly defined parmaterisation
type QueryParam struct {
	// URL-decoded query param key
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// URL-decoded query param value
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryParam) Reset()         { *m = QueryParam{} }
func (m *QueryParam) String() string { return proto.CompactTextString(m) }
func (*QueryParam) ProtoMessage()    {}
func (*QueryParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{2}
}

func (m *QueryParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryParam.Unmarshal(m, b)
}
func (m *QueryParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryParam.Marshal(b, m, deterministic)
}
func (m *QueryParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParam.Merge(m, src)
}
func (m *QueryParam) XXX_Size() int {
	return xxx_messageInfo_QueryParam.Size(m)
}
func (m *QueryParam) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParam.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParam proto.InternalMessageInfo

func (m *QueryParam) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *QueryParam) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterEnum("httpgrpc.Method", Method_name, Method_value)
	proto.RegisterType((*Request)(nil), "httpgrpc.Request")
	proto.RegisterType((*Response)(nil), "httpgrpc.Response")
	proto.RegisterType((*QueryParam)(nil), "httpgrpc.QueryParam")
}

func init() { proto.RegisterFile("proxy.proto", fileDescriptor_700b50b08ed8dbaf) }

var fileDescriptor_700b50b08ed8dbaf = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x51, 0x5d, 0x8f, 0xd3, 0x30,
	0x10, 0xbc, 0x34, 0xcd, 0xd7, 0x06, 0x4e, 0x66, 0x75, 0x0f, 0x11, 0x42, 0x22, 0xca, 0x53, 0x84,
	0x50, 0x85, 0x0a, 0x7f, 0xa0, 0xe4, 0x2c, 0x0e, 0x01, 0x49, 0x70, 0x7d, 0xe2, 0x11, 0x85, 0xc4,
	0xe2, 0x10, 0x2d, 0x36, 0x4e, 0x52, 0x9a, 0x9f, 0xc2, 0xbf, 0x45, 0x4e, 0x5a, 0x85, 0xbe, 0xed,
	0xcc, 0xac, 0x77, 0xbc, 0x3b, 0x10, 0x2a, 0x2d, 0x8f, 0xc3, 0x4a, 0x69, 0xd9, 0x49, 0xf4, 0x1f,
	0xba, 0x4e, 0x7d, 0xd7, 0xaa, 0x4e, 0xfe, 0x5a, 0xe0, 0x31, 0xf1, 0xbb, 0x17, 0x6d, 0x87, 0x29,
	0xb8, 0x7b, 0xd1, 0x3d, 0xc8, 0x26, 0xb2, 0x62, 0x2b, 0xbd, 0x5e, 0x93, 0xd5, 0xb9, 0x6d, 0xf5,
	0x69, 0xe4, 0xd9, 0x49, 0xc7, 0x67, 0x10, 0x28, 0x2d, 0x6b, 0xd1, 0xf4, 0x5a, 0x44, 0x8b, 0xd8,
	0x4a, 0x03, 0x36, 0x13, 0x18, 0x81, 0xa7, 0xaa, 0x61, 0x27, 0xab, 0x26, 0xb2, 0x63, 0x2b, 0x7d,
	0xc4, 0xce, 0x10, 0x5f, 0x82, 0xab, 0x2a, 0x5d, 0xed, 0xdb, 0x68, 0x19, 0xdb, 0x69, 0xb8, 0xbe,
	0x99, 0x1d, 0x3e, 0xf7, 0x42, 0x0f, 0xa5, 0x11, 0xd9, 0xa9, 0x27, 0xa1, 0xe0, 0x33, 0xd1, 0x2a,
	0xf9, 0xab, 0x15, 0xf8, 0x1c, 0xc2, 0xb6, 0xab, 0xba, 0xbe, 0xfd, 0x5a, 0xcb, 0x46, 0x8c, 0x1f,
	0x7c, 0xcc, 0x60, 0xa2, 0x32, 0xd9, 0x5c, 0x98, 0x2e, 0x2e, 0x4c, 0x93, 0x37, 0x00, 0xf3, 0x70,
	0x24, 0x60, 0xff, 0x14, 0xc3, 0x38, 0x20, 0x60, 0xa6, 0xc4, 0x1b, 0x70, 0x0e, 0xd5, 0xae, 0x3f,
	0x2f, 0x32, 0x81, 0x17, 0x7f, 0xc0, 0x9d, 0x96, 0xc6, 0x10, 0xbc, 0xfb, 0xfc, 0x43, 0x5e, 0x7c,
	0xc9, 0xc9, 0x15, 0x7a, 0x60, 0xbf, 0xa3, 0x9c, 0x58, 0xe8, 0xc3, 0xf2, 0x8e, 0x6e, 0x6e, 0xc9,
	0xc2, 0x54, 0x65, 0xb1, 0xe5, 0xc4, 0x36, 0x62, 0x79, 0xcf, 0xc9, 0x12, 0x01, 0xdc, 0x5b, 0xfa,
	0x91, 0x72, 0x4a, 0x1c, 0xf3, 0x3c, 0x2b, 0xf2, 0x9c, 0x66, 0x9c, 0xb8, 0x06, 0x14, 0x25, 0x7f,
	0x5f, 0xe4, 0x5b, 0xe2, 0x61, 0x00, 0x0e, 0x67, 0x9b, 0x8c, 0x12, 0xdf, 0x94, 0xe5, 0x86, 0x67,
	0x77, 0x24, 0x58, 0xbf, 0x85, 0x6b, 0x7a, 0x54, 0xb2, 0x15, 0xcd, 0x56, 0xe8, 0xc3, 0x8f, 0x5a,
	0xe0, 0x2b, 0x70, 0x4a, 0x13, 0x1e, 0x3e, 0x99, 0xcf, 0x75, 0xca, 0xec, 0x29, 0xfe, 0x4f, 0x4d,
	0xb7, 0x4a, 0xae, 0xbe, 0xb9, 0x63, 0xcc, 0xaf, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x9b,
	0xb5, 0xd3, 0xf5, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExposedServiceClient is the client API for ExposedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExposedServiceClient interface {
	// Proxies a message to the internal GRPC API
	Proxy(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type exposedServiceClient struct {
	cc *grpc.ClientConn
}

func NewExposedServiceClient(cc *grpc.ClientConn) ExposedServiceClient {
	return &exposedServiceClient{cc}
}

func (c *exposedServiceClient) Proxy(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/httpgrpc.ExposedService/Proxy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExposedServiceServer is the server API for ExposedService service.
type ExposedServiceServer interface {
	// Proxies a message to the internal GRPC API
	Proxy(context.Context, *Request) (*Response, error)
}

// UnimplementedExposedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedExposedServiceServer struct {
}

func (*UnimplementedExposedServiceServer) Proxy(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Proxy not implemented")
}

func RegisterExposedServiceServer(s *grpc.Server, srv ExposedServiceServer) {
	s.RegisterService(&_ExposedService_serviceDesc, srv)
}

func _ExposedService_Proxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExposedServiceServer).Proxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/httpgrpc.ExposedService/Proxy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExposedServiceServer).Proxy(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExposedService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "httpgrpc.ExposedService",
	HandlerType: (*ExposedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Proxy",
			Handler:    _ExposedService_Proxy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proxy.proto",
}
