package codegen

import "fmt"

const codegenmarker = `/**
 * Code generated by httpgrpc. DO NOT EDIT.
 * versions:
 * 	httpgrpc %s
 * 	protoc   %s
 * source: %s
 */

`

func getCodeGenmarker(version, protocVersion, sourceFile string) string {
	return fmt.Sprintf(codegenmarker, version, protocVersion, sourceFile)
}
