/**
 * Code generated by mercury. DO NOT EDIT.
 * versions:
 * 	mercury v0.8.0
 * 	protoc   v3.10.1
 * source: service.proto
 */

import * as packages from "__packages__";
import * as mercury_packages from "__packages__/mercury";
import * as mercury from "@llkennedy/mercury";

/** A service client */
export class ExposedAppClient extends mercury.Client {
	public async Random(req: mercury_packages.service.RandomRequest): Promise<mercury_packages.service.RandomResponse> {
		return this.SendUnary<mercury_packages.service.RandomRequest, mercury_packages.service.RandomResponse>("/Random", mercury.HTTPMethod.GET, req, mercury_packages.service.RandomResponse.Parse);
	}
	public async UploadPhoto(req: mercury_packages.service.UploadPhotoRequest): Promise<mercury_packages.service.UploadPhotoResponse> {
		return this.SendUnary<mercury_packages.service.UploadPhotoRequest, mercury_packages.service.UploadPhotoResponse>("/UploadPhoto", mercury.HTTPMethod.POST, req, mercury_packages.service.UploadPhotoResponse.Parse);
	}
	public async Feed(): Promise<mercury.IClientStream<mercury_packages.service.FeedData, mercury_packages.service.FeedResponse>> {
		return this.StartClientStream<mercury_packages.service.FeedData, mercury_packages.service.FeedResponse>("/Feed", mercury_packages.service.FeedResponse.Parse);
	}
	public async Broadcast(req: mercury_packages.service.BroadcastRequest): Promise<mercury.IServerStream<mercury_packages.service.BroadcastData>> {
		return this.StartServerStream<mercury_packages.service.BroadcastRequest, mercury_packages.service.BroadcastData>("/Broadcast", req, mercury_packages.service.BroadcastData.Parse);
	}
	public async ConvertToString(): Promise<mercury.IDualStream<mercury_packages.service.ConvertInput, mercury_packages.service.ConvertOutput>> {
		return this.StartDualStream<mercury_packages.service.ConvertInput, mercury_packages.service.ConvertOutput>("/ConvertToString", mercury_packages.service.ConvertOutput.Parse);
	}
}

/** A message */
export class FeedData extends packages.service.FeedData implements mercury.ProtoJSONCompatible {
	public ToProtoJSON(): Object {
		return {
			id: mercury.ToProtoJSON.String(this.id),
			dataType: mercury.ToProtoJSON.StringNumber(this.dataType),
			rawData: mercury.ToProtoJSON.Bytes(this.rawData),
		};
	}
	public static async Parse(data: any): Promise<FeedData> {
		let objData: Object = mercury.AnyToObject(data);
		let res = new FeedData();
		res.id = await mercury.Parse.String(objData, "id", "id");
		res.dataType = await mercury.Parse.Number(objData, "dataType", "data_type");
		res.rawData = await mercury.Parse.Bytes(objData, "rawData", "raw_data");
		return res;
	}
}

/** A message */
export class FeedResponse extends packages.service.FeedResponse implements mercury.ProtoJSONCompatible {
	public ToProtoJSON(): Object {
		return {
			received: mercury.ToProtoJSON.Number(this.received),
		};
	}
	public static async Parse(data: any): Promise<FeedResponse> {
		let objData: Object = mercury.AnyToObject(data);
		let res = new FeedResponse();
		res.received = await mercury.Parse.Number(objData, "received", "received");
		return res;
	}
}

/** A message */
export class BroadcastRequest extends packages.service.BroadcastRequest implements mercury.ProtoJSONCompatible {
	public ToProtoJSON(): Object {
		return {
			id: mercury.ToProtoJSON.String(this.id),
		};
	}
	public static async Parse(data: any): Promise<BroadcastRequest> {
		let objData: Object = mercury.AnyToObject(data);
		let res = new BroadcastRequest();
		res.id = await mercury.Parse.String(objData, "id", "id");
		return res;
	}
}

/** A message */
export class BroadcastData extends packages.service.BroadcastData implements mercury.ProtoJSONCompatible {
	public ToProtoJSON(): Object {
		return {
			rawData: mercury.ToProtoJSON.Bytes(this.rawData),
		};
	}
	public static async Parse(data: any): Promise<BroadcastData> {
		let objData: Object = mercury.AnyToObject(data);
		let res = new BroadcastData();
		res.rawData = await mercury.Parse.Bytes(objData, "rawData", "raw_data");
		return res;
	}
}

/** A message */
export class ConvertInput extends packages.service.ConvertInput implements mercury.ProtoJSONCompatible {
	public ToProtoJSON(): Object {
		return {
			rawData: mercury.ToProtoJSON.Bytes(this.rawData),
		};
	}
	public static async Parse(data: any): Promise<ConvertInput> {
		let objData: Object = mercury.AnyToObject(data);
		let res = new ConvertInput();
		res.rawData = await mercury.Parse.Bytes(objData, "rawData", "raw_data");
		return res;
	}
}

/** A message */
export class ConvertOutput extends packages.service.ConvertOutput implements mercury.ProtoJSONCompatible {
	public ToProtoJSON(): Object {
		return {
			convertedData: mercury.ToProtoJSON.String(this.convertedData),
		};
	}
	public static async Parse(data: any): Promise<ConvertOutput> {
		let objData: Object = mercury.AnyToObject(data);
		let res = new ConvertOutput();
		res.convertedData = await mercury.Parse.String(objData, "convertedData", "converted_data");
		return res;
	}
}

/** A message */
export class FibonacciRequest extends packages.service.FibonacciRequest implements mercury.ProtoJSONCompatible {
	public ToProtoJSON(): Object {
		return {
			n: mercury.ToProtoJSON.StringNumber(this.n),
		};
	}
	public static async Parse(data: any): Promise<FibonacciRequest> {
		let objData: Object = mercury.AnyToObject(data);
		let res = new FibonacciRequest();
		res.n = await mercury.Parse.Number(objData, "n", "n");
		return res;
	}
}

/** A message */
export class FibonacciResponse extends packages.service.FibonacciResponse implements mercury.ProtoJSONCompatible {
	public ToProtoJSON(): Object {
		return {
			number: mercury.ToProtoJSON.StringNumber(this.number),
		};
	}
	public static async Parse(data: any): Promise<FibonacciResponse> {
		let objData: Object = mercury.AnyToObject(data);
		let res = new FibonacciResponse();
		res.number = await mercury.Parse.Number(objData, "number", "number");
		return res;
	}
}

/** A message */
export class RandomRequest extends packages.service.RandomRequest implements mercury.ProtoJSONCompatible {
	public ToProtoJSON(): Object {
		return {
			lowerBound: mercury.ToProtoJSON.StringNumber(this.lowerBound),
			upperBound: mercury.ToProtoJSON.StringNumber(this.upperBound),
		};
	}
	public static async Parse(data: any): Promise<RandomRequest> {
		let objData: Object = mercury.AnyToObject(data);
		let res = new RandomRequest();
		res.lowerBound = await mercury.Parse.Number(objData, "lowerBound", "lower_bound");
		res.upperBound = await mercury.Parse.Number(objData, "upperBound", "upper_bound");
		return res;
	}
}

/** A message */
export class RandomResponse extends packages.service.RandomResponse implements mercury.ProtoJSONCompatible {
	public ToProtoJSON(): Object {
		return {
			number: mercury.ToProtoJSON.StringNumber(this.number),
		};
	}
	public static async Parse(data: any): Promise<RandomResponse> {
		let objData: Object = mercury.AnyToObject(data);
		let res = new RandomResponse();
		res.number = await mercury.Parse.Number(objData, "number", "number");
		return res;
	}
}

/** A message */
export class UploadPhotoRequest extends packages.service.UploadPhotoRequest implements mercury.ProtoJSONCompatible {
	public ToProtoJSON(): Object {
		return {
			data: mercury.ToProtoJSON.Bytes(this.data),
		};
	}
	public static async Parse(data: any): Promise<UploadPhotoRequest> {
		let objData: Object = mercury.AnyToObject(data);
		let res = new UploadPhotoRequest();
		res.data = await mercury.Parse.Bytes(objData, "data", "data");
		return res;
	}
}

/** A message */
export class UploadPhotoResponse extends packages.service.UploadPhotoResponse implements mercury.ProtoJSONCompatible {
	public ToProtoJSON(): Object {
		return {
			uuid: mercury.ToProtoJSON.String(this.uuid),
		};
	}
	public static async Parse(data: any): Promise<UploadPhotoResponse> {
		let objData: Object = mercury.AnyToObject(data);
		let res = new UploadPhotoResponse();
		res.uuid = await mercury.Parse.String(objData, "uuid", "uuid");
		return res;
	}
}

