// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FibonacciRequest struct {
	// The 1-indexed point in the Fibonacci sequence
	N                    uint64   `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FibonacciRequest) Reset()         { *m = FibonacciRequest{} }
func (m *FibonacciRequest) String() string { return proto.CompactTextString(m) }
func (*FibonacciRequest) ProtoMessage()    {}
func (*FibonacciRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *FibonacciRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FibonacciRequest.Unmarshal(m, b)
}
func (m *FibonacciRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FibonacciRequest.Marshal(b, m, deterministic)
}
func (m *FibonacciRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FibonacciRequest.Merge(m, src)
}
func (m *FibonacciRequest) XXX_Size() int {
	return xxx_messageInfo_FibonacciRequest.Size(m)
}
func (m *FibonacciRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FibonacciRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FibonacciRequest proto.InternalMessageInfo

func (m *FibonacciRequest) GetN() uint64 {
	if m != nil {
		return m.N
	}
	return 0
}

type FibonacciResponse struct {
	// The number found in the nth place of the sequence
	Number               uint64   `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FibonacciResponse) Reset()         { *m = FibonacciResponse{} }
func (m *FibonacciResponse) String() string { return proto.CompactTextString(m) }
func (*FibonacciResponse) ProtoMessage()    {}
func (*FibonacciResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *FibonacciResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FibonacciResponse.Unmarshal(m, b)
}
func (m *FibonacciResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FibonacciResponse.Marshal(b, m, deterministic)
}
func (m *FibonacciResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FibonacciResponse.Merge(m, src)
}
func (m *FibonacciResponse) XXX_Size() int {
	return xxx_messageInfo_FibonacciResponse.Size(m)
}
func (m *FibonacciResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FibonacciResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FibonacciResponse proto.InternalMessageInfo

func (m *FibonacciResponse) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type RandomRequest struct {
	// The lowest inclusive integer for the resulting random number
	LowerBound int64 `protobuf:"varint,1,opt,name=lower_bound,json=lowerBound,proto3" json:"lower_bound,omitempty"`
	// The highest inclusive integer for the resulting random number
	UpperBound           int64    `protobuf:"varint,2,opt,name=upper_bound,json=upperBound,proto3" json:"upper_bound,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RandomRequest) Reset()         { *m = RandomRequest{} }
func (m *RandomRequest) String() string { return proto.CompactTextString(m) }
func (*RandomRequest) ProtoMessage()    {}
func (*RandomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *RandomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RandomRequest.Unmarshal(m, b)
}
func (m *RandomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RandomRequest.Marshal(b, m, deterministic)
}
func (m *RandomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RandomRequest.Merge(m, src)
}
func (m *RandomRequest) XXX_Size() int {
	return xxx_messageInfo_RandomRequest.Size(m)
}
func (m *RandomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RandomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RandomRequest proto.InternalMessageInfo

func (m *RandomRequest) GetLowerBound() int64 {
	if m != nil {
		return m.LowerBound
	}
	return 0
}

func (m *RandomRequest) GetUpperBound() int64 {
	if m != nil {
		return m.UpperBound
	}
	return 0
}

type RandomResponse struct {
	// The generated number
	Number               int64    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RandomResponse) Reset()         { *m = RandomResponse{} }
func (m *RandomResponse) String() string { return proto.CompactTextString(m) }
func (*RandomResponse) ProtoMessage()    {}
func (*RandomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *RandomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RandomResponse.Unmarshal(m, b)
}
func (m *RandomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RandomResponse.Marshal(b, m, deterministic)
}
func (m *RandomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RandomResponse.Merge(m, src)
}
func (m *RandomResponse) XXX_Size() int {
	return xxx_messageInfo_RandomResponse.Size(m)
}
func (m *RandomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RandomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RandomResponse proto.InternalMessageInfo

func (m *RandomResponse) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type UploadPhotoRequest struct {
	// The raw bytes of the photo
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadPhotoRequest) Reset()         { *m = UploadPhotoRequest{} }
func (m *UploadPhotoRequest) String() string { return proto.CompactTextString(m) }
func (*UploadPhotoRequest) ProtoMessage()    {}
func (*UploadPhotoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *UploadPhotoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadPhotoRequest.Unmarshal(m, b)
}
func (m *UploadPhotoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadPhotoRequest.Marshal(b, m, deterministic)
}
func (m *UploadPhotoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadPhotoRequest.Merge(m, src)
}
func (m *UploadPhotoRequest) XXX_Size() int {
	return xxx_messageInfo_UploadPhotoRequest.Size(m)
}
func (m *UploadPhotoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadPhotoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadPhotoRequest proto.InternalMessageInfo

func (m *UploadPhotoRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UploadPhotoResponse struct {
	// The uuid generated to identify and retreive this photo
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadPhotoResponse) Reset()         { *m = UploadPhotoResponse{} }
func (m *UploadPhotoResponse) String() string { return proto.CompactTextString(m) }
func (*UploadPhotoResponse) ProtoMessage()    {}
func (*UploadPhotoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *UploadPhotoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadPhotoResponse.Unmarshal(m, b)
}
func (m *UploadPhotoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadPhotoResponse.Marshal(b, m, deterministic)
}
func (m *UploadPhotoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadPhotoResponse.Merge(m, src)
}
func (m *UploadPhotoResponse) XXX_Size() int {
	return xxx_messageInfo_UploadPhotoResponse.Size(m)
}
func (m *UploadPhotoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadPhotoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadPhotoResponse proto.InternalMessageInfo

func (m *UploadPhotoResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
	proto.RegisterType((*FibonacciRequest)(nil), "service.FibonacciRequest")
	proto.RegisterType((*FibonacciResponse)(nil), "service.FibonacciResponse")
	proto.RegisterType((*RandomRequest)(nil), "service.RandomRequest")
	proto.RegisterType((*RandomResponse)(nil), "service.RandomResponse")
	proto.RegisterType((*UploadPhotoRequest)(nil), "service.UploadPhotoRequest")
	proto.RegisterType((*UploadPhotoResponse)(nil), "service.UploadPhotoResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x8d, 0x0d, 0x2d, 0x99, 0xb6, 0xa2, 0x23, 0x54, 0x8d, 0x82, 0x65, 0x4f, 0x11, 0xa1,
	0x07, 0xbd, 0x7b, 0x10, 0x51, 0xf0, 0xa4, 0x2b, 0x9e, 0x25, 0x7f, 0x16, 0x0c, 0xb4, 0x3b, 0x6b,
	0xb2, 0xab, 0x1f, 0xd6, 0x2f, 0x23, 0xdd, 0xcd, 0x2e, 0xad, 0xcd, 0x6d, 0xe7, 0xcd, 0x2f, 0x6f,
	0x66, 0x1e, 0x81, 0x69, 0x2b, 0x9a, 0xef, 0xba, 0x14, 0x0b, 0xd5, 0x90, 0x26, 0x1c, 0x75, 0x25,
	0x9b, 0xc3, 0xe1, 0x63, 0x5d, 0x90, 0xcc, 0xcb, 0xb2, 0xe6, 0xe2, 0xcb, 0x88, 0x56, 0xe3, 0x04,
	0x22, 0x79, 0x1a, 0xcd, 0xa3, 0x2c, 0xe6, 0x91, 0x64, 0xd7, 0x70, 0xb4, 0x41, 0xb4, 0x8a, 0x64,
	0x2b, 0x70, 0x06, 0x43, 0x69, 0x56, 0x85, 0x68, 0x3a, 0xae, 0xab, 0xd8, 0x2b, 0x4c, 0x79, 0x2e,
	0x2b, 0x5a, 0x79, 0xaf, 0x4b, 0x18, 0x2f, 0xe9, 0x47, 0x34, 0x1f, 0x05, 0x19, 0x59, 0x59, 0x7a,
	0xc0, 0xc1, 0x4a, 0xf7, 0x6b, 0x65, 0x0d, 0x18, 0xa5, 0x02, 0xb0, 0xef, 0x00, 0x2b, 0x59, 0x80,
	0x65, 0x70, 0xe0, 0x2d, 0x7b, 0x87, 0x0f, 0xc2, 0xf0, 0x0c, 0xf0, 0x5d, 0x2d, 0x29, 0xaf, 0x5e,
	0x3e, 0x49, 0x93, 0xdf, 0x00, 0x21, 0xae, 0x72, 0x9d, 0x5b, 0x76, 0xc2, 0xed, 0x9b, 0x5d, 0xc1,
	0xf1, 0x16, 0xd9, 0x19, 0x23, 0xc4, 0xc6, 0xd4, 0x6e, 0xcb, 0x84, 0xdb, 0xf7, 0xcd, 0x6f, 0x04,
	0xa3, 0x37, 0x17, 0x16, 0x3e, 0x40, 0x12, 0xa2, 0xc0, 0xb3, 0x85, 0x8f, 0xf4, 0x7f, 0x80, 0x69,
	0xda, 0xd7, 0x72, 0x33, 0xd8, 0x1e, 0xde, 0x41, 0xf2, 0x24, 0xb4, 0xbb, 0x09, 0x67, 0x01, 0xdd,
	0xca, 0x2d, 0x3d, 0xd9, 0xd1, 0xc3, 0xf7, 0xcf, 0x30, 0xde, 0x58, 0x1e, 0xcf, 0x03, 0xb9, 0x7b,
	0x7c, 0x7a, 0xd1, 0xdf, 0xf4, 0x5e, 0xc5, 0xd0, 0xfe, 0x0e, 0xb7, 0x7f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x1c, 0x52, 0x15, 0x39, 0x1f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	// Fibonacci returns the nth number in the Fibonacci sequence. It does not start with an HTTP method and is therefore not exposed
	Fibonacci(ctx context.Context, in *FibonacciRequest, opts ...grpc.CallOption) (*FibonacciResponse, error)
	// GetRandom returns a random integer in the desired range. It may be accessed via a Get request to the proxy at, for example, /api/Service/Random
	GetRandom(ctx context.Context, in *RandomRequest, opts ...grpc.CallOption) (*RandomResponse, error)
	// UploadPhoto allows the upload of a photo to some persistence store. It may be accessed via  Post request to the proxy at, for example, /api/Service/UploadPhoto
	UploadPhoto(ctx context.Context, in *UploadPhotoRequest, opts ...grpc.CallOption) (*UploadPhotoResponse, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Fibonacci(ctx context.Context, in *FibonacciRequest, opts ...grpc.CallOption) (*FibonacciResponse, error) {
	out := new(FibonacciResponse)
	err := c.cc.Invoke(ctx, "/service.Service/Fibonacci", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetRandom(ctx context.Context, in *RandomRequest, opts ...grpc.CallOption) (*RandomResponse, error) {
	out := new(RandomResponse)
	err := c.cc.Invoke(ctx, "/service.Service/GetRandom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) UploadPhoto(ctx context.Context, in *UploadPhotoRequest, opts ...grpc.CallOption) (*UploadPhotoResponse, error) {
	out := new(UploadPhotoResponse)
	err := c.cc.Invoke(ctx, "/service.Service/UploadPhoto", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	// Fibonacci returns the nth number in the Fibonacci sequence. It does not start with an HTTP method and is therefore not exposed
	Fibonacci(context.Context, *FibonacciRequest) (*FibonacciResponse, error)
	// GetRandom returns a random integer in the desired range. It may be accessed via a Get request to the proxy at, for example, /api/Service/Random
	GetRandom(context.Context, *RandomRequest) (*RandomResponse, error)
	// UploadPhoto allows the upload of a photo to some persistence store. It may be accessed via  Post request to the proxy at, for example, /api/Service/UploadPhoto
	UploadPhoto(context.Context, *UploadPhotoRequest) (*UploadPhotoResponse, error)
}

// UnimplementedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (*UnimplementedServiceServer) Fibonacci(ctx context.Context, req *FibonacciRequest) (*FibonacciResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fibonacci not implemented")
}
func (*UnimplementedServiceServer) GetRandom(ctx context.Context, req *RandomRequest) (*RandomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRandom not implemented")
}
func (*UnimplementedServiceServer) UploadPhoto(ctx context.Context, req *UploadPhotoRequest) (*UploadPhotoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadPhoto not implemented")
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_Fibonacci_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FibonacciRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Fibonacci(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Service/Fibonacci",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Fibonacci(ctx, req.(*FibonacciRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetRandom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetRandom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Service/GetRandom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetRandom(ctx, req.(*RandomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_UploadPhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadPhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).UploadPhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Service/UploadPhoto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).UploadPhoto(ctx, req.(*UploadPhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fibonacci",
			Handler:    _Service_Fibonacci_Handler,
		},
		{
			MethodName: "GetRandom",
			Handler:    _Service_GetRandom_Handler,
		},
		{
			MethodName: "UploadPhoto",
			Handler:    _Service_UploadPhoto_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
