/**
 * Code generated by mercury. DO NOT EDIT.
 * versions:
 * 	mercury v0.8.0
 * 	protoc   v3.10.1
 * source: service.proto
 */

import * as mercury from "@llkennedy/mercury";
import { RandomRequest, RandomResponse, UploadPhotoRequest, UploadPhotoResponse, FeedData, FeedResponse, BroadcastRequest, BroadcastData, ConvertInput, ConvertOutput } from "service";

export class ExposedAppClient extends mercury.Client {
	constructor(basePath: string | undefined = "localhost/api", useTLS: boolean | undefined = true, client: mercury.AxiosInstance | undefined = undefined) {
		super(basePath, useTLS, client);
	}
	public async Random(req: RandomRequest): Promise<RandomResponse> {
		return this.SendUnary("Random", mercury.HTTPMethod.GET, req, RandomResponse.Parse)
	}
}