/**
 * Code generated by protoc-gen-tsjson. DO NOT EDIT.
 * versions:
 * 	protoc-gen-tsjson v0.3.0
 * 	protoc            v3.10.1
 * source: service.proto
 */

import * as packages from "__packages__";

/** An enum */
export enum FeedType {
	/** An enum value */
	FEED_TYPE_UNKNOWN = 0,
	/** An enum value */
	FEED_TYPE_RED = 1,
	/** An enum value */
	FEED_TYPE_BLUE = 2,
}

/** A message */
export class FeedData extends Object {
	/** A field */
	public id?: string;
	/** A field */
	public dataType?: number;
	/** A field */
	public rawData?: Uint8Array;
	/** A field */
	public type?: packages.service.FeedType;
}

/** A message */
export class FeedResponse extends Object {
	/** A field */
	public received?: number;
}

/** A message */
export class BroadcastRequest extends Object {
	/** A field */
	public id?: string;
}

/** A message */
export class BroadcastData extends Object {
	/** A field */
	public rawData?: Uint8Array;
}

/** A message */
export class ConvertInput extends Object {
	/** A field */
	public rawData?: Uint8Array;
}

/** A message */
export class ConvertOutput extends Object {
	/** A field */
	public convertedData?: string;
}

/** A message */
export class FibonacciRequest extends Object {
	/** A field */
	public n?: number;
}

/** A message */
export class FibonacciResponse extends Object {
	/** A field */
	public number?: number;
}

/** A message */
export class RandomRequest extends Object {
	/** A field */
	public lowerBound?: number;
	/** A field */
	public upperBound?: number;
}

/** A message */
export class RandomResponse extends Object {
	/** A field */
	public number?: number;
}

/** A message */
export class UploadPhotoRequest extends Object {
	/** A field */
	public data?: Uint8Array;
}

/** A message */
export class UploadPhotoResponse extends Object {
	/** A field */
	public uuid?: string;
}

