/**
 * Code generated by httpgrpc. DO NOT EDIT.
 * versions:
 * 	httpgrpc v0.8.0
 * 	protoc   v3.10.1
 * source: service.proto
 */

import * as packages from "__packages__";
import * as httpgrpc_packages from "__packages__/httpgrpc";
import * as httpgrpc from "@llkennedy/httpgrpc";

/** A message */
export class FeedData extends packages.service.FeedData implements httpgrpc.ProtoJSONCompatible {
}

/** A message */
export class FeedResponse extends packages.service.FeedResponse implements httpgrpc.ProtoJSONCompatible {
}

/** A message */
export class BroadcastRequest extends packages.service.BroadcastRequest implements httpgrpc.ProtoJSONCompatible {
}

/** A message */
export class BroadcastData extends packages.service.BroadcastData implements httpgrpc.ProtoJSONCompatible {
}

/** A message */
export class ConvertInput extends packages.service.ConvertInput implements httpgrpc.ProtoJSONCompatible {
}

/** A message */
export class ConvertOutput extends packages.service.ConvertOutput implements httpgrpc.ProtoJSONCompatible {
}

/** A message */
export class FibonacciRequest extends packages.service.FibonacciRequest implements httpgrpc.ProtoJSONCompatible {
}

/** A message */
export class FibonacciResponse extends packages.service.FibonacciResponse implements httpgrpc.ProtoJSONCompatible {
}

/** A message */
export class RandomRequest extends packages.service.RandomRequest implements httpgrpc.ProtoJSONCompatible {
}

/** A message */
export class RandomResponse extends packages.service.RandomResponse implements httpgrpc.ProtoJSONCompatible {
}

/** A message */
export class UploadPhotoRequest extends packages.service.UploadPhotoRequest implements httpgrpc.ProtoJSONCompatible {
}

/** A message */
export class UploadPhotoResponse extends packages.service.UploadPhotoResponse implements httpgrpc.ProtoJSONCompatible {
}

