/**
 * Code generated by httpgrpc. DO NOT EDIT.
 * versions:
 * 	httpgrpc v0.8.0
 * 	protoc   v3.10.1
 * source: service.proto
 */

import * as packages from "__packages__";
import * as httpgrpc_packages from "__packages__/httpgrpc";
import * as httpgrpc from "@llkennedy/httpgrpc";

/** A service client */
export class ExposedAppClient extends httpgrpc.Client {
	public async Random(req: httpgrpc_packages.service.RandomRequest): Promise<httpgrpc_packages.service.RandomResponse> {
		return this.SendUnary<httpgrpc_packages.service.RandomRequest, httpgrpc_packages.service.RandomResponse>("/Random", httpgrpc.HTTPMethod.GET, req, httpgrpc_packages.service.RandomResponse.Parse);
	}
	public async UploadPhoto(req: httpgrpc_packages.service.UploadPhotoRequest): Promise<httpgrpc_packages.service.UploadPhotoResponse> {
		return this.SendUnary<httpgrpc_packages.service.UploadPhotoRequest, httpgrpc_packages.service.UploadPhotoResponse>("/UploadPhoto", httpgrpc.HTTPMethod.POST, req, httpgrpc_packages.service.UploadPhotoResponse.Parse);
	}
	public async Feed(): Promise<httpgrpc.IClientStream<httpgrpc_packages.service.FeedData, httpgrpc_packages.service.FeedResponse>> {
		return this.StartClientStream<httpgrpc_packages.service.FeedData, httpgrpc_packages.service.FeedResponse>("/Feed", httpgrpc_packages.service.FeedResponse.Parse);
	}
	public async Broadcast(req: httpgrpc_packages.service.BroadcastRequest): Promise<httpgrpc.IServerStream<httpgrpc_packages.service.BroadcastData>> {
		return this.StartServerStream<httpgrpc_packages.service.BroadcastRequest, httpgrpc_packages.service.BroadcastData>("/Broadcast", req, httpgrpc_packages.service.BroadcastData.Parse);
	}
	public async ConvertToString(): Promise<httpgrpc.IDualStream<httpgrpc_packages.service.ConvertInput, httpgrpc_packages.service.ConvertOutput>> {
		return this.StartDualStream<httpgrpc_packages.service.ConvertInput, httpgrpc_packages.service.ConvertOutput>("/ConvertToString", httpgrpc_packages.service.ConvertOutput.Parse);
	}
}

/** A message */
export class FeedData extends packages.service.FeedData implements httpgrpc.ProtoJSONCompatible {
	public ToProtoJSON(): Object {
		throw new Error("unimplemented")
	}
	public static async Parse(data: any): Promise<FeedData> {
		throw new Error("unimplemented");
	}
}

/** A message */
export class FeedResponse extends packages.service.FeedResponse implements httpgrpc.ProtoJSONCompatible {
	public ToProtoJSON(): Object {
		throw new Error("unimplemented")
	}
	public static async Parse(data: any): Promise<FeedResponse> {
		throw new Error("unimplemented");
	}
}

/** A message */
export class BroadcastRequest extends packages.service.BroadcastRequest implements httpgrpc.ProtoJSONCompatible {
	public ToProtoJSON(): Object {
		throw new Error("unimplemented")
	}
	public static async Parse(data: any): Promise<BroadcastRequest> {
		throw new Error("unimplemented");
	}
}

/** A message */
export class BroadcastData extends packages.service.BroadcastData implements httpgrpc.ProtoJSONCompatible {
	public ToProtoJSON(): Object {
		throw new Error("unimplemented")
	}
	public static async Parse(data: any): Promise<BroadcastData> {
		throw new Error("unimplemented");
	}
}

/** A message */
export class ConvertInput extends packages.service.ConvertInput implements httpgrpc.ProtoJSONCompatible {
	public ToProtoJSON(): Object {
		throw new Error("unimplemented")
	}
	public static async Parse(data: any): Promise<ConvertInput> {
		throw new Error("unimplemented");
	}
}

/** A message */
export class ConvertOutput extends packages.service.ConvertOutput implements httpgrpc.ProtoJSONCompatible {
	public ToProtoJSON(): Object {
		throw new Error("unimplemented")
	}
	public static async Parse(data: any): Promise<ConvertOutput> {
		throw new Error("unimplemented");
	}
}

/** A message */
export class FibonacciRequest extends packages.service.FibonacciRequest implements httpgrpc.ProtoJSONCompatible {
	public ToProtoJSON(): Object {
		throw new Error("unimplemented")
	}
	public static async Parse(data: any): Promise<FibonacciRequest> {
		throw new Error("unimplemented");
	}
}

/** A message */
export class FibonacciResponse extends packages.service.FibonacciResponse implements httpgrpc.ProtoJSONCompatible {
	public ToProtoJSON(): Object {
		throw new Error("unimplemented")
	}
	public static async Parse(data: any): Promise<FibonacciResponse> {
		throw new Error("unimplemented");
	}
}

/** A message */
export class RandomRequest extends packages.service.RandomRequest implements httpgrpc.ProtoJSONCompatible {
	public ToProtoJSON(): Object {
		throw new Error("unimplemented")
	}
	public static async Parse(data: any): Promise<RandomRequest> {
		throw new Error("unimplemented");
	}
}

/** A message */
export class RandomResponse extends packages.service.RandomResponse implements httpgrpc.ProtoJSONCompatible {
	public ToProtoJSON(): Object {
		throw new Error("unimplemented")
	}
	public static async Parse(data: any): Promise<RandomResponse> {
		throw new Error("unimplemented");
	}
}

/** A message */
export class UploadPhotoRequest extends packages.service.UploadPhotoRequest implements httpgrpc.ProtoJSONCompatible {
	public ToProtoJSON(): Object {
		throw new Error("unimplemented")
	}
	public static async Parse(data: any): Promise<UploadPhotoRequest> {
		throw new Error("unimplemented");
	}
}

/** A message */
export class UploadPhotoResponse extends packages.service.UploadPhotoResponse implements httpgrpc.ProtoJSONCompatible {
	public ToProtoJSON(): Object {
		throw new Error("unimplemented")
	}
	public static async Parse(data: any): Promise<UploadPhotoResponse> {
		throw new Error("unimplemented");
	}
}

